### ISSUE TITLE
Update README to use "image" instead of "file" for Output

### ISSUE THREAD

**Issue by artworx** [armStrapTools/armStrap#29]
The sample from the README: 

```
[Output]
file = armStrap.img
size = 2048
```

But `file = armStrap.img` is ignored and `device = /dev/mmcblk0` is used instead. 

Turns out the documentation is outdated, the correct key to use is `image`: 

```
[Output]
image = armStrap.img
size = 2048
```

**Comment by EddyBeaupre** [comment]
Yep! miss that one. Thanks for catching it!
